### ISSUE TITLE
Can't build on iOS (Yi360Demo)

### ISSUE THREAD

**Issue by marcos10soares** [YITechnology/YIOpenAPI#10]
When trying to build Yi360Demo for iOS it gives the following errors:

'ActionCameraListener' is unavailable: cannot find Swift declaration for this class
'Error' is unavailable: cannot find Swift declaration for this class
'Super' is unavailable: cannot find Swift declaration for this class

Method does not override any method from its superclass Camera.swift (regarding override func onConnected)

Tried with Xcode:
8.1
8.0
7.3.1

iOS - 9.3.4

Thanks

**Comment by marcos10soares** [comment]
I deleted the frameworks (CocoaASyncSocket, YiCamerasSDK, SwiftyJSON) and dragged them again to the project and now was able to build.

But when running I only get a blank app screen and a fatal error, the console prints:
dyld: Library not loaded: @rpath/CocoaAsyncSocket.framework/CocoaAsyncSocket
  Referenced from: /var/containers/Bundle/Application/56BA9053-9FAD-4987-A290-1430C365AAFE/YI360Demo.app/YI360Demo
  Reason: image not found
(lldb)

**Comment by xieyubo** [comment]
You need add CocoAsyncSocket.framework to your library search path.

**Comment by marcos10soares** [comment]
@xieyubo thank you, but I added "$(SRCROOT)/YI360Demo" to the library search path and still have the blank screen and "lldb" on the console.

dyld`dyld_fatal_error:
->  0x120059088 <+0>: brk    #0x3

**Comment by JaviLorbada** [comment]
@marcos10soares I got it working with the following search path in the build settings of the project

<img width="758" alt="screenshot 2017-02-03 15 45 05" src="https://cloud.githubusercontent.com/assets/1939155/22595454/d69bd16c-ea27-11e6-89fe-d770cfab47c5.png">

I hope with that works :)
