### ISSUE TITLE
Does it support streaming?

### ISSUE THREAD

**Issue by andreivdev** [YITechnology/YIOpenAPI#27]
Hello,

I noticed you are using an Android app as an example but I'm working on a java app on desktop.
Does you API support video streaming at low resolution like your YI Action app does? If not, will it in the near future?

Thank you, have a great day!

**Comment by andreivoinea93** [comment]
I managed to do it.

**Comment by philwindsor** [comment]
hi @andreivoinea93. Did you manage to get streaming working without having to use the QR code scanner?
