### ISSUE TITLE
Live streaming to an Android device

### ISSUE THREAD

**Issue by philjoseph** [YITechnology/YIOpenAPI#3]
Hello - I am interested to develop an Android app that will capture the live stream of your dash cam. Would this SDK enables this scenario ? Is this doable via Wifi Direct ? Via other connectivity? 

Thanks in advance - Philippe

**Comment by philjoseph** [comment]
I want to add that it is great also to capture GPS data in addition to the video stream.

**Comment by taoma618** [comment]
This SDK is for YI 4K Action Camera at this moment. We will add live stream support to the SDK pretty soon.
