### ISSUE TITLE
Swift 3.1

### ISSUE THREAD

**Issue by stefkampen** [YITechnology/YIOpenAPI#40]
Can you update the Swift SDK to Swift 3.1?

**Comment by astoj** [comment]
Or update the framework so Carthage can run its magic

Carthage error message:
*** Skipped building YIOpenAPI due to the error:
Dependency "YIOpenAPI" has no shared framework schemes for any of the platforms: iOS

**Comment by JaviLorbada** [comment]
any plans or date for this update @taoma618 @xieyubo @yitechnology-admin?
