### ISSUE TITLE
Xcode 8.3  doesn't support 3.01 swift

### ISSUE THREAD

**Issue by PyHuT** [YITechnology/YIOpenAPI#41]
Can't use sdk with new Xcode 8.3. When updates (if they will)?

**Comment by huos3203** [comment]
YIOpenAPI/sdk/swift/samples/YI360Demo/Camera.swift:19:8: Module compiled with Swift 3.0.1 cannot be imported in Swift 3.1
YICameraSDK.framework/Modules/YICameraSDK.swiftmodule/x86_64.swiftmodule
