### ISSUE TITLE
Is it possible to reset the image counter?

### ISSUE THREAD

**Issue by rahmatnazali** [YITechnology/YIOpenAPI#52]
Can I somehow reset the camera's image counter, so that it can start to name the captured image to `/100MEDIA/YDXJ0001.JPG` again?

I tried to reset the camera setting but it did not seems to be worked.

Thanks in advance.

**Comment by Water-bamboo** [comment]
It's not supported yet. Sorry for inconvenient.
How about do a bunch rename from PC software?

**Comment by rahmatnazali** [comment]
Hi, thanks for the reply!

It's okay for now. I already find a workaround to manually counting the image to find its full path :))

Best regards,
rahmat
