### ISSUE TITLE
Automatically capture single pictures with 1Hz (endlessly)

### ISSUE THREAD

**Issue by hb0** [YITechnology/YIOpenAPI#53]
Hi. I'm interested in useing this camera for a project of mine where we need to capture single shots (with EIS as it's in a moving environment) with multiple cameras with 1 Hz until we ask the cameras to stop (after multiple hours).
Is this possible with the YI 4k? The "video time lapse" function looks like it's automatically processing the captured shots - but we need the single shots (1HZ). The simultaneous start of multiple cameras should not be a problem as far as I understood.

**Comment by Water-bamboo** [comment]
What is 1HZ single shots? Could you explain more?

**Comment by hb0** [comment]
Like time-laps where single pictures are captured with auto-focus, auto-iso, etc - each second (i.e. with 1Hz) and stored as pictures (not rendered to a video format). This mode should be able to capture pictures until a "stop" command is sent - for multiple hours (e.g. 6 h = 6*3600 pictures)

**Comment by NikolayRag** [comment]
Use "Photo time lapse", did you?
I haven't try hours, but atm 10 minutes are going ok.
The only issue is that timing seems to be quite uneven.

**Comment by hb0** [comment]
Thanks Nikolay. I don't have the camera here right now so I can't do further test at the moment. But the "uneven timing" is a problem our use case can't live with unfortunately. Cheers
