### ISSUE TITLE
YI Action Camera develop

### ISSUE THREAD

**Issue by tommutter** [YITechnology/YIOpenAPI#6]
Hi, when following the instructions on the website to upgrade our YI action camera, we cannot find the right firmware. The device's SN starts with "Z25L" which doesn't match any SN on the official website.

We also tried the firmware in this repository, but didn't success. Can the YI action camera (not the 4k version) support this firmware? How can we get the device upgraded successfully?

**Comment by taoma618** [comment]
The firmware found on this repository is for YI 4K Action Camera only. 

Please contact support@yitechnology.com for your YI Action Camera firmware upgrade problems.
