### ISSUE TITLE
Swift 4.1

### ISSUE THREAD

**Issue by killerfeature** [YITechnology/YIOpenAPI#74]
Can you please update SDK for newest XCode and Swift support?

**Comment by M9236059933** [comment]
+1

**Comment by jtmorris314** [comment]
+1

**Comment by jtmorris314** [comment]
Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1: .../YIOpenAPI/sdk/swift/samples/../framework/iphonesimulator/YICameraSDK.framework/Modules/YICameraSDK.swiftmodule/arm64.swiftmodule

**Comment by hendibr** [comment]
Is there any workaround for that ?

**Comment by killerfeature** [comment]
no hope
